zn.define([
    './ZNPluginAdminConfig',
    './ZNPluginAdminMenu',
    './ZNPluginAdminProject',
    './ZNPluginAdminProjectBug',
    './ZNPluginAdminRole',
    './ZNPluginAdminUser',
    './ZNPluginAdminUserLog',
    './ZNPluginAdminVar'
]);
